name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov boto3
    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-report=term-missing --cov-report=xml
    - name: Generate coverage badge
      run: |
        coverage=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); print(round(float(root.attrib['line-rate']) * 100, 2))")
        echo "coverage=$coverage" >> $GITHUB_ENV
        if (( $(echo "$coverage >= 90" | bc -l) )); then
          color="brightgreen"
        elif (( $(echo "$coverage >= 70" | bc -l) )); then
          color="yellow"
        else
          color="red"
        fi
        echo "color=$color" >> $GITHUB_ENV
    - name: Update coverage badge
      run: |
        sed -i "s/coverage-[0-9]*%25-[a-z]*/coverage-${coverage}%25-${color}/" README.md
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update coverage badge to ${coverage}%" || true
        git push || true
