name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install setuptools pytest pytest-cov pytest-mock --upgrade pip 
        for dir in */source-*; do
          if [ -d "$dir" ]; then
            echo "Installing dependencies for $dir"
            (cd "$dir" && pip install '.[dev]')
          fi
        done
    - name: Run tests with coverage
      run: |
        # Run tests and generate XML report
        python -m pytest --cov=./ --cov-report=term-missing --cov-report=xml

        # Function to determine color based on coverage
        get_color() {
          local coverage=$1
          if (( $(echo "$coverage >= 90" | bc -l) )); then
            echo "brightgreen"
          elif (( $(echo "$coverage >= 80" | bc -l) )); then
            echo "green"
          elif (( $(echo "$coverage >= 70" | bc -l) )); then
            echo "yellow"
          else
            echo "red"
          fi
        }

        # Parse XML coverage report
        while IFS= read -r line; do
          if [[ $line =~ filename=\"([^\"]+)\" ]]; then
            filepath="${BASH_REMATCH[1]}"
            
            # Extract project name from path
            if [[ $filepath =~ ^([^/]+)/ ]]; then
              project_name="${BASH_REMATCH[1]}"
              
              if [[ $project_name != "tests" && $project_name != "." ]]; then
                # Get coverage for this file
                if [[ $line =~ line-rate=\"([^\"]+)\" ]]; then
                  coverage=$(echo "${BASH_REMATCH[1]} * 100" | bc | cut -d. -f1)
                  color=$(get_color $coverage)
                  echo "Found project: $project_name with coverage: $coverage%"
                  
                  # Update project's README
                  project_readme="${project_name}/README.md"
                  if [ -f "$project_readme" ]; then
                    # Add or update coverage badge in project README
                    if ! grep -q "Test Coverage" "$project_readme"; then
                      # Add badge after the first heading
                      sed -i "1s/^/![Test Coverage](https:\/\/img.shields.io\/badge\/coverage-${coverage}%25-${color})\n\n/" "$project_readme"
                    else
                      # Update existing badge
                      sed -i "s/coverage-[0-9.]*%25/coverage-${coverage}%25/" "$project_readme"
                      sed -i "s/brightgreen\|green\|yellow\|red/${color}/" "$project_readme"
                    fi
                  fi
                fi
              fi
            fi
          elif [[ $line =~ ^\<coverage.*line-rate=\"([^\"]+)\" ]]; then
            total_coverage=$(echo "${BASH_REMATCH[1]} * 100" | bc | cut -d. -f1)
            total_color=$(get_color $total_coverage)
            echo "Total coverage: $total_coverage%"
            # Update total coverage badge in root README
            sed -i "s/coverage-[0-9.]*%25/coverage-${total_coverage}%25/" README.md
            sed -i "s/brightgreen\|green\|yellow\|red/${total_color}/" README.md
          fi
        done < coverage.xml

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md */README.md
        git commit -m "Update coverage badges [skip ci]" || exit 0
        git push
